print()
print("n_neighbors: ")
print("     This parameter determines the number of neighbors used in ")
print("     the local connectivity structure of the data. It controls the balance ")
print("     between preserving local and global structure in the embedding. Larger ")
print("     values will result in more global structure being preserved, but may also ")
print("     lead to more smoothing of the data. Smaller values will focus more on ")
print("     local structure but can be influenced by noise and result in less ")
print("     meaningful embeddings.")
print("     Start with a small value, such as 5 or 10, and gradually increase ")
print("     it to observe the effects on the resulting embedding.")
print("     Plot the resulting embeddings and inspect how the data points are ")
print("     distributed. Look for clusters, separability, and preservation of ")
print("     local and global structure.")
print("     If the embedding appears too compact or clusters are not well-defined, ")
print("     consider increasing the n_neighbors value.")
print("     If the embedding is too scattered or lacks clear structure, consider ")
print("     decreasing the n_neighbors value.")
print()
print("min_dist: ")
print("     This parameter controls how tightly the embedded points ")
print("     are packed together. It measures the minimum distance between points ")
print("     in the low-dimensional space. Higher values encourage points to be ")
print("     more evenly distributed, while lower values allow points to be closer ")
print("     together.")
print("     Start with a larger value, such as 0.5 or 0.8, to encourage more even ")
print("     spacing of the points.")
print("     Gradually decrease the min_dist value to bring the points closer together ")
print("     while monitoring the effects on the embedding.")
print("     Be cautious not to set min_dist too low, as it may result in overfitting ")
print("     and poor generalization.")
print("     If the embedding appears too crowded or lacks separation between clusters, ")
print("     consider increasing the min_dist value.")
print("     If the embedding is too spread out or lacks clear boundaries, consider ")
print("     decreasing the min_dist value.")
print()
